---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.88.1/hugo_0.88.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.88.1_Linux-64bit.deb

script:
  - hugo -D

after_success:
  - # Set your identification.
  - ls -la
  - git config --global user.email "encryptgig@gmail.com"
  - git config --global user.name "encryptgig"
  -
  - # Clone some repository you want into "repo" subfolder.
  - mkdir web
  - git clone https://${GH_TOKEN}@github.com/encryptgig/website.git ./web
  - cd web
  - ls -la
  - # Now, perform your custom actions. Custom repository is cloned int "repo" subfolder of PWD.
  - ls -la blogs/
  - # After your actions are done, you might want to commit and push your changes.
  - rm -rf blogs/public
  - ls -la blogs/
  - cp -r ../public blogs/
  - ls -la blogs/
  - git add .
  - git commit -m "update from travis"
  - git push origin main
  - git log

