---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.88.1/hugo_0.88.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.88.1_Linux-64bit.deb

script:
  - hugo -D

after_success:
  - # Set your identification.
  - git config --global user.email "encryptgig@gmail.com"
  - git config --global user.name "encryptgig"
  -
  - # Clone some repository you want into "repo" subfolder.
  - mkdir web
  - git clone https://${GH_TOKEN}@github.com/encryptgig/website.git
  - cd website
  - ls -la website
