title = "Notre-Dame de Paris"
baseURL = "https://encryptgig.com/blogs/public"
languageCode = "en-us"
theme = "ananke"
#themesDir = "../.."
#resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "EncryptGig Blog"
    weight = 1
    contentDir = "content"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/encryptgig_favicon.png"
  site_logo = ""
  description = "We secure"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/encryptgig-inc-953251211/?originalSubdomain=in"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/slide-1.jpeg"
  recent_posts_number = 6